name = "auth-worker"
main = "./src/index.ts"
compatibility_date = "2024-05-01"

# Common KV namespaces (for production)
[[kv_namespaces]]
binding = "CF_KV_CREDENTIALS"
id = "3c946fc92ef84fd58d11c670d2e4120b"  # Your production KV namespace ID

[vars]
CF_ENCRYPTION_KEY = "YOUR-32-BYTE-BASE64-KEY"
NODE_ENV = "production"

# Production routes (applies to default environment)
[[triggers.routes]]
pattern = "auth-worker.gerrygugger.workers.dev/*"

# Development environment
[env.dev]
name = "auth-worker-dev"

# Development routes
[env.dev.triggers]
routes = [
  { pattern = "dev-auth-worker.gerrygugger.workers.dev/*" }
]

# KV namespace for dev (using same as production for now)
[[env.dev.kv_namespaces]]
binding = "CF_KV_CREDENTIALS"
id = "3c946fc92ef84fd58d11c670d2e4120b"  # Same as production for now

# Environment variables for dev
[env.dev.vars]
NODE_ENV = "development"
# Local-only; override with real key via .env or shell export
CF_ENCRYPTION_KEY = "YOUR-32-BYTE-BASE64-KEY"