name = "auth-worker"
main = "./src/index.ts"
compatibility_date = "2024-05-01"

[[kv_namespaces]]
binding = "CF_KV_CREDENTIALS"
id = "${CF_KV_CREDENTIALS_ID}"
preview_id = "${CF_KV_CREDENTIALS_PREVIEW_ID}"

[vars]
CF_ENCRYPTION_KEY = "YOUR-32-BYTE-BASE64-KEY"
NODE_ENV = "production"

[env.dev]
name = "auth-worker-dev"

[env.dev.vars]
NODE_ENV = "development"