name = "flaim-auth"
main = "src/index.ts"
compatibility_date = "2024-12-01"

# Stripe & JWT secrets (set via wrangler secret put)
# STRIPE_API_KEY
# STRIPE_WEBHOOK_SECRET  
# JWT_SECRET

# KV for subscription caching
[[kv_namespaces]]
binding = "SUBSCRIPTION_KV"
id = "flaim_subscription_cache"

# Routes for authentication flow
[[routes]]
pattern = "auth.flaim.app/*"
zone_name = "flaim.app"

[[routes]]
pattern = "*/login"
zone_name = "gerrygugger.workers.dev"

[[routes]]
pattern = "*/checkout" 
zone_name = "gerrygugger.workers.dev"

[[routes]]
pattern = "*/callback"
zone_name = "gerrygugger.workers.dev"

[[routes]]
pattern = "*/webhook/stripe"
zone_name = "gerrygugger.workers.dev"

[env.dev]
name = "flaim-auth-dev"

[[env.dev.kv_namespaces]]
binding = "SUBSCRIPTION_KV"
id = "flaim_subscription_cache_dev"

[[env.dev.routes]]
pattern = "flaim-auth-dev.gerrygugger.workers.dev/*"

[env.prod]
name = "flaim-auth-prod"

[[env.prod.kv_namespaces]]
binding = "SUBSCRIPTION_KV"
id = "flaim_subscription_cache_prod"

[[env.prod.routes]]
pattern = "auth.flaim.app/*"