name = "flaim-auth"
main = "src/index.ts"
compatibility_date = "2024-12-01"

# Stripe & JWT secrets (set via wrangler secret put)
# STRIPE_API_KEY
# STRIPE_WEBHOOK_SECRET  
# JWT_SECRET

# Cron job for quarterly key rotation
[triggers]
crons = ["0 0 1 */3 *"] # Every 3 months on the 1st at midnight

# KV for subscription caching
[[kv_namespaces]]
binding = "SUBSCRIPTION_KV"
id = "flaim_subscription_cache"

# KV for JWT key management and rotation
[[kv_namespaces]]
binding = "JWT_KEYS_KV"
id = "flaim_jwt_keys"

# Routes for authentication flow - specific paths to avoid conflicts
[[routes]]
pattern = "flaim-auth.gerrygugger.workers.dev/*"
zone_name = "gerrygugger.workers.dev"

[[routes]]
pattern = "*/login"
zone_name = "gerrygugger.workers.dev"

[[routes]]
pattern = "*/checkout" 
zone_name = "gerrygugger.workers.dev"

[[routes]]
pattern = "*/callback"
zone_name = "gerrygugger.workers.dev"

[[routes]]
pattern = "*/webhook/stripe"
zone_name = "gerrygugger.workers.dev"

[[routes]]
pattern = "*/validate"
zone_name = "gerrygugger.workers.dev"

[[routes]]
pattern = "*/jwt/jwks"
zone_name = "gerrygugger.workers.dev"

[env.dev]
name = "flaim-auth-dev"

[[env.dev.kv_namespaces]]
binding = "SUBSCRIPTION_KV"
id = "flaim_subscription_cache_dev"

[[env.dev.kv_namespaces]]
binding = "JWT_KEYS_KV"
id = "flaim_jwt_keys_dev"

[[env.dev.routes]]
pattern = "flaim-auth-dev.gerrygugger.workers.dev/*"

[env.prod]
name = "flaim-auth-prod"

[[env.prod.kv_namespaces]]
binding = "SUBSCRIPTION_KV"
id = "flaim_subscription_cache_prod"

[[env.prod.kv_namespaces]]
binding = "JWT_KEYS_KV"
id = "flaim_jwt_keys_prod"

[[env.prod.routes]]
pattern = "auth.flaim.app/*"

[[env.prod.routes]]
pattern = "flaim-auth.gerrygugger.workers.dev/*"