name = "baseball-espn-mcp"
main = "src/index.ts"
compatibility_date = "2024-12-01"

# Default environment variables
[vars]
NODE_ENV = "production"
AUTH_WORKER_URL = "http://localhost:8786"

# Environment secrets (set via wrangler secret put)
# CF_ENCRYPTION_KEY (for ESPN credential storage)
# CLERK_SECRET_KEY (for server-side verification)

# KV bindings for user credential storage
# Using existing CRED_KV namespace
[[kv_namespaces]]
binding = "CF_KV_CREDENTIALS"
id = "3c946fc92ef84fd58d11c670d2e4120b"           # CRED_KV namespace
preview_id = "3c946fc92ef84fd58d11c670d2e4120b"  # Using same ID for preview

# Custom routes commented out for now - use default workers.dev URL
# [[routes]]
# pattern = "baseball-espn-mcp.gerrygugger.workers.dev/*"
# zone_name = "gerrygugger.workers.dev"

# [[routes]]
# pattern = "espn-mcp.gerrygugger.workers.dev/*"
# zone_name = "gerrygugger.workers.dev"

[env.dev]
name = "baseball-espn-mcp-dev"

[env.dev.vars]
NODE_ENV = "development"
AUTH_WORKER_URL = "http://localhost:8786"

[[env.dev.kv_namespaces]]
binding = "CF_KV_CREDENTIALS"
id = "3c946fc92ef84fd58d11c670d2e4120b"        # CRED_KV namespace
preview_id = "3c946fc92ef84fd58d11c670d2e4120b"

# [[env.dev.routes]]
# pattern = "baseball-espn-mcp-dev.gerrygugger.workers.dev/*"
# zone_name = "gerrygugger.workers.dev"

[env.prod]
name = "baseball-espn-mcp-prod"

[env.prod.vars]
NODE_ENV = "production"
AUTH_WORKER_URL = "https://auth-worker-prod.your-subdomain.workers.dev"

[[env.prod.kv_namespaces]]
binding = "CF_KV_CREDENTIALS"
id = "3c946fc92ef84fd58d11c670d2e4120b"       # CRED_KV namespace
preview_id = "3c946fc92ef84fd58d11c670d2e4120b"

# [[env.prod.routes]]
# pattern = "baseball-espn-mcp.gerrygugger.workers.dev/*"
# zone_name = "gerrygugger.workers.dev"

# [[env.prod.routes]]
# pattern = "espn-mcp.gerrygugger.workers.dev/*"
# zone_name = "gerrygugger.workers.dev"