name = "baseball-espn-mcp"
main = "src/index.ts"
compatibility_date = "2024-12-01"

# Default environment variables
[vars]
NODE_ENV = "production"
AUTH_WORKER_URL = "https://auth-worker.gerrygugger.workers.dev"

# Environment secrets (set via wrangler secret put)
# CF_ENCRYPTION_KEY (for ESPN credential storage)
# CLERK_SECRET_KEY (for server-side verification)

# KV bindings for user credential storage
# Using existing CRED_KV namespace
[[kv_namespaces]]
binding = "CF_KV_CREDENTIALS"
id = "3c946fc92ef84fd58d11c670d2e4120b"           # CRED_KV namespace
preview_id = "3c946fc92ef84fd58d11c670d2e4120b"  # Using same ID for preview

# Production routes (applies to default environment)
[[triggers.routes]]
pattern = "baseball-espn-mcp.gerrygugger.workers.dev/*"

# Development environment
[env.dev]
name = "baseball-espn-mcp-dev"

# Development routes
[env.dev.triggers]
routes = [
  { pattern = "dev-baseball-espn-mcp.gerrygugger.workers.dev/*" }
]

# Environment variables for dev
[env.dev.vars]
NODE_ENV = "development"
AUTH_WORKER_URL = "https://dev-auth-worker.gerrygugger.workers.dev"
name = "baseball-espn-mcp-dev"

[[env.dev.kv_namespaces]]
binding = "CF_KV_CREDENTIALS"
id = "3c946fc92ef84fd58d11c670d2e4120b"        # CRED_KV namespace
preview_id = "3c946fc92ef84fd58d11c670d2e4120b"

# [[env.dev.routes]]
# pattern = "baseball-espn-mcp-dev.gerrygugger.workers.dev/*"
# zone_name = "gerrygugger.workers.dev"

[env.prod]
name = "baseball-espn-mcp-prod"

[env.prod.vars]
NODE_ENV = "production"
AUTH_WORKER_URL = "https://auth-worker.gerrygugger.workers.dev"

[[env.prod.kv_namespaces]]
binding = "CF_KV_CREDENTIALS"
id = "3c946fc92ef84fd58d11c670d2e4120b"       # CRED_KV namespace
preview_id = "3c946fc92ef84fd58d11c670d2e4120b"

# [[env.prod.routes]]
# pattern = "baseball-espn-mcp.gerrygugger.workers.dev/*"
# zone_name = "gerrygugger.workers.dev"

# [[env.prod.routes]]
# pattern = "espn-mcp.gerrygugger.workers.dev/*"
# zone_name = "gerrygugger.workers.dev"