name = "football-espn-mcp"
main = "src/index.ts"
compatibility_date = "2024-12-01"

# Default environment variables
[vars]
NODE_ENV = "production"
AUTH_WORKER_URL = "http://localhost:8786"

# Environment secrets (set via wrangler secret put)
# CF_ENCRYPTION_KEY (for ESPN credential storage)
# CLERK_SECRET_KEY (for production security)

# KV bindings for user credential storage  
# Using existing CRED_KV namespace (shared with baseball worker)
[[kv_namespaces]]
binding = "CF_KV_CREDENTIALS"
id = "3c946fc92ef84fd58d11c670d2e4120b"           # CRED_KV namespace (shared)
preview_id = "3c946fc92ef84fd58d11c670d2e4120b"  # Using same ID for preview

[env.dev]
name = "football-espn-mcp-dev"

[env.dev.vars]
NODE_ENV = "development"
AUTH_WORKER_URL = "http://localhost:8786"

[[env.dev.kv_namespaces]]
binding = "CF_KV_CREDENTIALS"
id = "3c946fc92ef84fd58d11c670d2e4120b"        # CRED_KV namespace (shared)
preview_id = "3c946fc92ef84fd58d11c670d2e4120b"

[env.prod]
name = "football-espn-mcp-prod"

[env.prod.vars]
NODE_ENV = "production"
AUTH_WORKER_URL = "https://auth-worker-prod.your-subdomain.workers.dev"

[[env.prod.kv_namespaces]]
binding = "CF_KV_CREDENTIALS"
id = "3c946fc92ef84fd58d11c670d2e4120b"       # CRED_KV namespace (shared)
preview_id = "3c946fc92ef84fd58d11c670d2e4120b"