name = "football-espn-mcp"
main = "src/index.ts"
compatibility_date = "2024-12-01"

# Default environment variables (production)
[vars]
NODE_ENV = "production"
AUTH_WORKER_URL = "https://auth-worker.gerrygugger.workers.dev"

# Environment secrets (set via wrangler secret put)
# CF_ENCRYPTION_KEY (for ESPN credential storage)
# CLERK_SECRET_KEY (for production security)

# KV bindings for user credential storage  
# Using existing CRED_KV namespace (shared with baseball worker)
[[kv_namespaces]]
binding = "CF_KV_CREDENTIALS"
id = "3c946fc92ef84fd58d11c670d2e4120b"           # CRED_KV namespace (shared)
preview_id = "3c946fc92ef84fd58d11c670d2e4120b"  # Using same ID for preview

# Production routes (applies to default environment)
[[triggers.routes]]
pattern = "football-espn-mcp.gerrygugger.workers.dev/*"

# Development environment
[env.dev]
name = "football-espn-mcp-dev"

# Development routes
[env.dev.triggers]
routes = [
  { pattern = "dev-football-espn-mcp.gerrygugger.workers.dev/*" }
]

# Environment variables for dev
[env.dev.vars]
NODE_ENV = "development"
AUTH_WORKER_URL = "https://dev-auth-worker.gerrygugger.workers.dev"

# KV namespace for dev
[[env.dev.kv_namespaces]]
binding = "CF_KV_CREDENTIALS"
id = "3c946fc92ef84fd58d11c670d2e4120b"  # CRED_KV namespace (shared)
preview_id = "3c946fc92ef84fd58d11c670d2e4120b"