-- Flaim Supabase greenfield baseline.
--
-- This file is intentionally secret-free and data-free. It describes the
-- reviewed application-owned schema as observed on 2026-07-27. Cleanup of
-- grants, GraphQL, duplicate indexes, and collation metadata belongs to later
-- forward-only migrations after isolated-preview verification.

create schema if not exists extensions;
create schema if not exists graphql;
create schema if not exists analytics;

create extension if not exists pg_cron with schema pg_catalog;
create extension if not exists pg_graphql with schema graphql;
create extension if not exists pg_stat_statements with schema extensions;
create extension if not exists pgcrypto with schema extensions;
create extension if not exists supabase_vault with schema vault;
create extension if not exists "uuid-ossp" with schema extensions;

do $$
begin
  if not exists (select 1 from pg_roles where rolname = 'analytics_readonly') then
    create role analytics_readonly nologin;
  end if;
end
$$;

create table public.espn_credentials (
  clerk_user_id text not null,
  swid text not null,
  s2 text not null,
  email text,
  updated_at timestamptz default timezone('utc'::text, now()),
  constraint espn_credentials_pkey primary key (clerk_user_id)
);

create table public.espn_leagues (
  id bigint generated by default as identity not null,
  clerk_user_id text not null,
  league_id text not null,
  sport text not null,
  team_id text,
  team_name text,
  league_name text,
  season_year integer,
  created_at timestamptz default timezone('utc'::text, now()),
  constraint espn_leagues_pkey primary key (id)
);

create table public.oauth_codes (
  id uuid default gen_random_uuid() not null,
  code text not null,
  user_id text not null,
  redirect_uri text not null,
  code_challenge text,
  code_challenge_method text,
  scope text default 'mcp:read'::text,
  expires_at timestamptz not null,
  used_at timestamptz,
  created_at timestamptz default now(),
  resource text,
  constraint oauth_codes_pkey primary key (id),
  constraint oauth_codes_code_key unique (code),
  constraint oauth_codes_code_challenge_method_check
    check (code_challenge_method = any (array['S256'::text, 'plain'::text]))
);

create table public.oauth_tokens (
  id uuid default gen_random_uuid() not null,
  access_token text not null,
  user_id text not null,
  scope text default 'mcp:read'::text,
  expires_at timestamptz not null,
  revoked_at timestamptz,
  refresh_token text,
  refresh_token_expires_at timestamptz,
  created_at timestamptz default now(),
  resource text,
  client_name text,
  grant_type text,
  constraint oauth_tokens_pkey primary key (id),
  constraint oauth_tokens_access_token_key unique (access_token),
  constraint oauth_tokens_refresh_token_key unique (refresh_token)
);

comment on column public.oauth_tokens.client_name is
  'AI platform name derived from redirect_uri (e.g., Claude, ChatGPT)';

create table public.oauth_states (
  id uuid default gen_random_uuid() not null,
  state text not null,
  redirect_uri text not null,
  client_id text,
  expires_at timestamptz not null,
  created_at timestamptz default now(),
  constraint oauth_states_pkey primary key (id),
  constraint oauth_states_state_key unique (state)
);

create table public.yahoo_credentials (
  clerk_user_id text not null,
  access_token text not null,
  refresh_token text not null,
  expires_at timestamptz not null,
  yahoo_guid text,
  created_at timestamptz default now(),
  updated_at timestamptz default now(),
  refresh_lease_owner text,
  refresh_lease_expires_at timestamptz,
  app_fingerprint text,
  constraint yahoo_credentials_pkey primary key (clerk_user_id)
);

create table public.yahoo_leagues (
  id uuid default gen_random_uuid() not null,
  clerk_user_id text not null,
  sport text not null,
  season_year integer not null,
  league_key text not null,
  league_name text not null,
  team_id text,
  team_key text,
  created_at timestamptz default now(),
  updated_at timestamptz default now(),
  team_name text,
  recurring_league_id text,
  constraint yahoo_leagues_pkey primary key (id),
  constraint yahoo_leagues_unique_user_league_season
    unique (clerk_user_id, league_key, season_year),
  constraint yahoo_leagues_sport_check
    check (sport = any (array[
      'football'::text,
      'baseball'::text,
      'basketball'::text,
      'hockey'::text
    ]))
);

create table public.platform_oauth_states (
  id uuid default gen_random_uuid() not null,
  state text not null,
  platform text not null,
  clerk_user_id text not null,
  redirect_after text,
  expires_at timestamptz not null,
  created_at timestamptz default now(),
  constraint platform_oauth_states_pkey primary key (id),
  constraint platform_oauth_states_state_key unique (state),
  constraint platform_oauth_states_platform_check
    check (platform = any (array['yahoo'::text, 'sleeper'::text, 'cbs'::text]))
);

create table public.user_preferences (
  clerk_user_id text not null,
  default_sport text,
  created_at timestamptz default now(),
  updated_at timestamptz default now(),
  default_football jsonb,
  default_baseball jsonb,
  default_basketball jsonb,
  default_hockey jsonb,
  constraint user_preferences_pkey primary key (clerk_user_id),
  constraint user_preferences_default_sport_check
    check (
      default_sport is null
      or default_sport = any (array[
        'football'::text,
        'baseball'::text,
        'basketball'::text,
        'hockey'::text
      ])
    )
);

comment on column public.user_preferences.default_football is
  'Default football league: { platform, leagueId, seasonYear } or null';
comment on column public.user_preferences.default_baseball is
  'Default baseball league: { platform, leagueId, seasonYear } or null';
comment on column public.user_preferences.default_basketball is
  'Default basketball league: { platform, leagueId, seasonYear } or null';
comment on column public.user_preferences.default_hockey is
  'Default hockey league: { platform, leagueId, seasonYear } or null';

create table public.sleeper_connections (
  clerk_user_id text not null,
  sleeper_user_id text not null,
  sleeper_username text,
  created_at timestamptz default now(),
  updated_at timestamptz default now(),
  constraint sleeper_connections_pkey primary key (clerk_user_id)
);

create table public.sleeper_leagues (
  id uuid default gen_random_uuid() not null,
  clerk_user_id text not null,
  league_id text not null,
  sport text not null,
  season_year integer not null,
  league_name text not null,
  roster_id integer,
  sleeper_user_id text not null,
  created_at timestamptz default now(),
  updated_at timestamptz default now(),
  recurring_league_id text,
  constraint sleeper_leagues_pkey primary key (id),
  constraint sleeper_leagues_unique
    unique (clerk_user_id, league_id, season_year)
);

create table public.chat_runs (
  id uuid default gen_random_uuid() not null,
  visitor_key text not null,
  preset_id text not null,
  model text not null,
  status text not null,
  error_code text,
  duration_ms integer,
  started_at timestamptz default now() not null,
  completed_at timestamptz,
  created_at timestamptz default now() not null,
  updated_at timestamptz default now() not null,
  constraint public_chat_runs_pkey primary key (id),
  constraint public_chat_runs_status_check
    check (status = any (array[
      'running'::text,
      'completed'::text,
      'error'::text,
      'aborted'::text,
      'rate_limited'::text,
      'concurrency_rejected'::text
    ]))
);

create table public.demo_context_cache (
  cache_key text not null,
  context_text text not null,
  expires_at timestamptz not null,
  created_at timestamptz default now() not null,
  updated_at timestamptz default now() not null,
  constraint public_chat_context_cache_pkey primary key (cache_key)
);

create table public.demo_answer_cache (
  cache_key text not null,
  preset_id text not null,
  sport text not null,
  provider text not null,
  provider_model text not null,
  context_version text not null,
  prompt_version text not null,
  answer_text text not null,
  answer_word_count integer,
  generated_at timestamptz not null,
  expires_at timestamptz not null,
  stale_after timestamptz not null,
  status text default 'ready'::text not null,
  generation_ms integer,
  source_meta jsonb default '{}'::jsonb not null,
  tool_trace_summary jsonb,
  created_at timestamptz default now() not null,
  updated_at timestamptz default now() not null,
  constraint public_demo_answer_cache_pkey primary key (cache_key)
);

create table public.demo_refresh_runs (
  id uuid default gen_random_uuid() not null,
  job_type text not null,
  preset_id text,
  sport text,
  provider_attempted text not null,
  provider_model text,
  status text not null,
  error_code text,
  error_message text,
  started_at timestamptz not null,
  completed_at timestamptz,
  duration_ms integer,
  source_meta jsonb default '{}'::jsonb not null,
  created_at timestamptz default now() not null,
  constraint public_demo_refresh_runs_pkey primary key (id)
);

create table public.demo_refresh_attempts (
  run_id text not null,
  job_type text default 'answer'::text not null,
  preset_id text not null,
  sport text not null,
  attempt_number integer not null,
  provider_attempted text not null,
  requested_model text,
  resolved_provider_model text,
  model_class text,
  model_family text,
  status text not null,
  retry_reason text,
  error_code text,
  error_message text,
  parse_status text,
  validation_status text,
  started_at timestamptz,
  completed_at timestamptz,
  duration_ms integer,
  answer_word_count integer,
  tool_call_count integer,
  used_fantasy_mcp boolean,
  used_web_search boolean,
  token_input integer,
  token_total integer,
  token_thoughts integer,
  stored_to_cache boolean default false not null,
  source_meta jsonb default '{}'::jsonb not null,
  created_at timestamptz default now() not null,
  constraint demo_refresh_attempts_pkey primary key (run_id, attempt_number)
);

create table public.demo_antigravity_cache (
  cache_key text not null,
  preset_id text not null,
  sport text not null,
  provider text not null,
  provider_model text not null,
  context_version text not null,
  prompt_version text not null,
  answer_text text not null,
  answer_word_count integer,
  generated_at timestamptz not null,
  expires_at timestamptz not null,
  stale_after timestamptz not null,
  status text default 'ready'::text not null,
  generation_ms integer,
  validation_status text,
  quality_warnings jsonb default '[]'::jsonb not null,
  source_meta jsonb default '{}'::jsonb not null,
  tool_trace_summary jsonb,
  created_at timestamptz default now() not null,
  updated_at timestamptz default now() not null,
  constraint demo_antigravity_cache_pkey primary key (cache_key)
);

comment on table public.demo_antigravity_cache is
  'Parallel candidate cache for Antigravity-generated Flaim demo answers. Not read by the live homepage until explicitly promoted.';

create table public.archived_leagues (
  id uuid default gen_random_uuid() not null,
  clerk_user_id text not null,
  platform text not null,
  sport text not null,
  recurring_league_id text not null,
  league_name text,
  archived_at timestamptz default now(),
  mode text default 'historical'::text not null,
  constraint archived_leagues_pkey primary key (id),
  constraint archived_leagues_unique
    unique (clerk_user_id, platform, sport, recurring_league_id),
  constraint archived_leagues_mode_check
    check (mode = any (array['historical'::text, 'hidden'::text])),
  constraint archived_leagues_platform_check
    check (platform = any (array['espn'::text, 'yahoo'::text, 'sleeper'::text])),
  constraint archived_leagues_sport_check
    check (sport = any (array[
      'football'::text,
      'baseball'::text,
      'basketball'::text,
      'hockey'::text
    ]))
);

create table public.mcp_tool_events (
  id bigint generated always as identity not null,
  ts timestamptz default now() not null,
  env text not null,
  user_id text not null,
  auth_type text not null,
  client_name text,
  tool_name text not null,
  platform text,
  sport text,
  status text not null,
  error_code text,
  latency_ms integer,
  league_hash text,
  constraint mcp_tool_events_pkey primary key (id)
);

create table public.mcp_user_daily (
  day date not null,
  env text not null,
  user_id text not null,
  auth_type text not null,
  client_name text default ''::text not null,
  call_count integer not null,
  constraint mcp_user_daily_pkey
    primary key (day, env, user_id, auth_type, client_name)
);

create table public.mcp_tool_daily (
  day date not null,
  env text not null,
  tool_name text not null,
  platform text default ''::text not null,
  sport text default ''::text not null,
  status text not null,
  call_count integer not null,
  p50_ms integer,
  p95_ms integer,
  auth_type text default ''::text not null,
  constraint mcp_tool_daily_pkey
    primary key (day, env, auth_type, tool_name, platform, sport, status)
);

create table public.provider_sync_state (
  clerk_user_id text not null,
  provider text not null,
  sync_lease_owner text,
  sync_lease_expires_at timestamptz,
  last_attempt_at timestamptz,
  last_success_at timestamptz,
  last_failure_at timestamptz,
  last_error_code text,
  last_error_message text,
  last_league_count integer,
  last_duration_ms integer,
  last_sync_source text,
  updated_at timestamptz default now() not null,
  constraint provider_sync_state_pkey primary key (clerk_user_id, provider),
  constraint provider_sync_state_provider_check
    check (provider = any (array['espn'::text, 'yahoo'::text, 'sleeper'::text]))
);

create table analytics.dashboard_snapshot (
  id integer default 1 not null,
  payload jsonb not null,
  computed_at timestamptz default now() not null,
  constraint dashboard_snapshot_pkey primary key (id),
  constraint dashboard_snapshot_known_rows check (id = any (array[1, 2]))
);

create table analytics.internal_users (
  user_id text not null,
  note text,
  added_at timestamptz default now() not null,
  constraint internal_users_pkey primary key (user_id)
);

alter table public.espn_credentials enable row level security;
alter table public.espn_leagues enable row level security;
alter table public.oauth_codes enable row level security;
alter table public.oauth_tokens enable row level security;
alter table public.oauth_states enable row level security;
alter table public.yahoo_credentials enable row level security;
alter table public.yahoo_leagues enable row level security;
alter table public.platform_oauth_states enable row level security;
alter table public.user_preferences enable row level security;
alter table public.sleeper_connections enable row level security;
alter table public.sleeper_leagues enable row level security;
alter table public.chat_runs enable row level security;
alter table public.demo_context_cache enable row level security;
alter table public.demo_answer_cache enable row level security;
alter table public.demo_refresh_runs enable row level security;
alter table public.demo_refresh_attempts enable row level security;
alter table public.demo_antigravity_cache enable row level security;
alter table public.archived_leagues enable row level security;
alter table public.mcp_tool_events enable row level security;
alter table public.mcp_user_daily enable row level security;
alter table public.mcp_tool_daily enable row level security;
alter table public.provider_sync_state enable row level security;

create index idx_archived_leagues_user
  on public.archived_leagues using btree (clerk_user_id);
create index idx_public_chat_runs_status_started
  on public.chat_runs using btree (status, started_at desc);
create index idx_public_chat_runs_visitor_started
  on public.chat_runs using btree (visitor_key, started_at desc);
create index idx_public_demo_answer_cache_expires_at
  on public.demo_answer_cache using btree (expires_at);
create index idx_public_demo_answer_cache_preset_sport
  on public.demo_answer_cache using btree (preset_id, sport);
create index idx_public_demo_answer_cache_stale_after
  on public.demo_answer_cache using btree (stale_after);
create index demo_antigravity_cache_generated_at_idx
  on public.demo_antigravity_cache using btree (generated_at desc);
create index demo_antigravity_cache_sport_preset_idx
  on public.demo_antigravity_cache using btree (sport, preset_id);
create index idx_public_chat_context_cache_expires_at
  on public.demo_context_cache using btree (expires_at);
create index demo_refresh_attempts_model_created_idx
  on public.demo_refresh_attempts using btree (requested_model, created_at desc);
create index demo_refresh_attempts_preset_created_idx
  on public.demo_refresh_attempts using btree (preset_id, created_at desc);
create index demo_refresh_attempts_status_created_idx
  on public.demo_refresh_attempts using btree (status, created_at desc);
create index idx_public_demo_refresh_runs_preset_sport_created
  on public.demo_refresh_runs using btree (preset_id, sport, created_at desc);
create index public_demo_refresh_runs_preset_sport_created_at_idx
  on public.demo_refresh_runs using btree (preset_id, sport, created_at desc);
create index public_demo_refresh_runs_sport_created_at_idx
  on public.demo_refresh_runs using btree (sport, created_at desc);
create unique index idx_espn_leagues_user_league_sport_season_unique
  on public.espn_leagues using btree (
    clerk_user_id,
    league_id,
    sport,
    coalesce(season_year, '-1'::integer)
  );
create index idx_leagues_user
  on public.espn_leagues using btree (clerk_user_id);
create index idx_mcp_events_ts
  on public.mcp_tool_events using btree (ts);
create index idx_mcp_events_user_ts
  on public.mcp_tool_events using btree (user_id, ts);
create index idx_oauth_codes_code
  on public.oauth_codes using btree (code);
create index idx_oauth_codes_expires_at
  on public.oauth_codes using btree (expires_at);
create index idx_oauth_states_expires_at
  on public.oauth_states using btree (expires_at);
create index idx_oauth_states_state
  on public.oauth_states using btree (state);
create index idx_oauth_tokens_access_token
  on public.oauth_tokens using btree (access_token);
create index idx_oauth_tokens_expires_at
  on public.oauth_tokens using btree (expires_at);
create index idx_oauth_tokens_refresh_token
  on public.oauth_tokens using btree (refresh_token);
create index idx_oauth_tokens_user_id
  on public.oauth_tokens using btree (user_id);
create index idx_platform_oauth_states_expires_at
  on public.platform_oauth_states using btree (expires_at);
create index idx_platform_oauth_states_state
  on public.platform_oauth_states using btree (state);
create index idx_sleeper_leagues_recurring
  on public.sleeper_leagues using btree (recurring_league_id);
create index idx_sleeper_leagues_user
  on public.sleeper_leagues using btree (clerk_user_id);
create index idx_yahoo_credentials_expires_at
  on public.yahoo_credentials using btree (expires_at);
create index idx_yahoo_leagues_recurring
  on public.yahoo_leagues using btree (recurring_league_id);
create index idx_yahoo_leagues_season
  on public.yahoo_leagues using btree (season_year);
create index idx_yahoo_leagues_sport
  on public.yahoo_leagues using btree (sport);
create index idx_yahoo_leagues_user_id
  on public.yahoo_leagues using btree (clerk_user_id);

create or replace function public.acquire_public_chat_run(
  p_visitor_key text,
  p_preset_id text,
  p_model text,
  p_max_concurrent integer default 1
)
returns table (
  allowed boolean,
  run_id uuid,
  rejection_reason text,
  concurrent_count integer
)
language plpgsql
set search_path to ''
as $function$
declare
  v_run_id uuid;
  v_concurrent_count integer;
begin
  perform pg_advisory_xact_lock(hashtext(p_visitor_key));

  update public.chat_runs
  set status = 'aborted',
      error_code = coalesce(error_code, 'stale_timeout'),
      completed_at = coalesce(completed_at, now()),
      updated_at = now()
  where visitor_key = p_visitor_key
    and status = 'running'
    and started_at < now() - interval '5 minutes';

  select count(*) into v_concurrent_count
  from public.chat_runs
  where visitor_key = p_visitor_key
    and status = 'running';

  if v_concurrent_count >= p_max_concurrent then
    insert into public.chat_runs (visitor_key, preset_id, model, status)
    values (p_visitor_key, p_preset_id, p_model, 'concurrency_rejected')
    returning id into v_run_id;

    return query
      select false, v_run_id, 'concurrency_limited', v_concurrent_count;
    return;
  end if;

  insert into public.chat_runs (visitor_key, preset_id, model, status)
  values (p_visitor_key, p_preset_id, p_model, 'running')
  returning id into v_run_id;

  return query
    select true, v_run_id, null::text, v_concurrent_count;
end;
$function$;

create or replace function public.complete_public_chat_run(
  p_run_id uuid,
  p_status text,
  p_duration_ms integer default null,
  p_error_code text default null
)
returns void
language plpgsql
set search_path to ''
as $function$
begin
  update public.chat_runs
  set status = p_status,
      duration_ms = p_duration_ms,
      error_code = p_error_code,
      completed_at = now(),
      updated_at = now()
  where id = p_run_id;
end;
$function$;

create or replace function public.cleanup_expired_oauth_codes()
returns integer
language plpgsql
set search_path to ''
as $function$
declare
  deleted_count integer;
begin
  delete from public.oauth_codes
  where expires_at < now()
     or used_at is not null;

  get diagnostics deleted_count = row_count;
  return deleted_count;
end;
$function$;

create or replace function public.cleanup_expired_oauth_states()
returns integer
language plpgsql
set search_path to ''
as $function$
declare
  deleted_count integer;
begin
  delete from public.oauth_states
  where expires_at < now();

  get diagnostics deleted_count = row_count;
  return deleted_count;
end;
$function$;

create or replace function public.cleanup_expired_platform_oauth_states()
returns integer
language plpgsql
set search_path to ''
as $function$
declare
  deleted_count integer;
begin
  delete from public.platform_oauth_states
  where expires_at < now();

  get diagnostics deleted_count = row_count;
  return deleted_count;
end;
$function$;

create or replace function public.cleanup_expired_oauth_ephemeral()
returns void
language plpgsql
set search_path to ''
as $function$
begin
  perform public.cleanup_expired_oauth_codes();
  perform public.cleanup_expired_oauth_states();
  perform public.cleanup_expired_platform_oauth_states();
end;
$function$;

create or replace function public.cleanup_expired_oauth_tokens()
returns integer
language plpgsql
set search_path to ''
as $function$
declare
  deleted_count integer;
begin
  delete from public.oauth_tokens
  where grant_type is distinct from 'authorization_code'
    and (
      (revoked_at is not null and revoked_at < now() - interval '7 days')
      or (
        revoked_at is null
        and refresh_token_expires_at is not null
        and refresh_token_expires_at < now()
      )
    );

  get diagnostics deleted_count = row_count;
  return deleted_count;
end;
$function$;

create or replace function public.prune_mcp_events()
returns integer
language plpgsql
set search_path to ''
as $function$
declare
  deleted_count integer;
begin
  delete from public.mcp_tool_events
  where ts < now() - interval '90 days';

  get diagnostics deleted_count = row_count;
  return deleted_count;
end;
$function$;

create or replace function public.rollup_mcp_usage(
  target_day date default (current_date - 1)
)
returns void
language plpgsql
set search_path to ''
as $function$
begin
  delete from public.mcp_user_daily
  where day = target_day;

  insert into public.mcp_user_daily (
    day,
    env,
    user_id,
    auth_type,
    client_name,
    call_count
  )
  select
    target_day,
    env,
    user_id,
    auth_type,
    coalesce(client_name, ''),
    count(*)
  from public.mcp_tool_events
  where ts >= target_day
    and ts < target_day + 1
  group by env, user_id, auth_type, coalesce(client_name, '');

  delete from public.mcp_tool_daily
  where day = target_day;

  insert into public.mcp_tool_daily (
    day,
    env,
    auth_type,
    tool_name,
    platform,
    sport,
    status,
    call_count,
    p50_ms,
    p95_ms
  )
  select
    target_day,
    env,
    auth_type,
    tool_name,
    coalesce(platform, ''),
    coalesce(sport, ''),
    status,
    count(*),
    percentile_cont(0.5) within group (order by latency_ms)::integer,
    percentile_cont(0.95) within group (order by latency_ms)::integer
  from public.mcp_tool_events
  where ts >= target_day
    and ts < target_day + 1
  group by
    env,
    auth_type,
    tool_name,
    coalesce(platform, ''),
    coalesce(sport, ''),
    status;
end;
$function$;

create view public.demo_refresh_attempt_scorecard_7d
with (security_invoker = true)
as
select
  preset_id,
  sport,
  requested_model,
  resolved_provider_model,
  count(*) filter (
    where coalesce((source_meta ->> 'dryRun')::boolean, false) = false
  ) as attempts,
  count(*) filter (
    where status = 'stored'
      and coalesce((source_meta ->> 'dryRun')::boolean, false) = false
  ) as stored_attempts,
  count(*) filter (
    where status = 'retry'
      and coalesce((source_meta ->> 'dryRun')::boolean, false) = false
  ) as retries,
  count(*) filter (
    where status = 'failed'
      and coalesce((source_meta ->> 'dryRun')::boolean, false) = false
  ) as failures,
  round(avg(duration_ms) filter (
    where coalesce((source_meta ->> 'dryRun')::boolean, false) = false
  )) as avg_duration_ms,
  percentile_disc(0.5) within group (order by duration_ms) filter (
    where coalesce((source_meta ->> 'dryRun')::boolean, false) = false
      and duration_ms is not null
  ) as p50_duration_ms,
  percentile_disc(0.95) within group (order by duration_ms) filter (
    where coalesce((source_meta ->> 'dryRun')::boolean, false) = false
      and duration_ms is not null
  ) as p95_duration_ms,
  round(avg(token_thoughts) filter (
    where coalesce((source_meta ->> 'dryRun')::boolean, false) = false
      and token_thoughts is not null
  )) as avg_token_thoughts
from public.demo_refresh_attempts
where created_at >= now() - interval '7 days'
group by preset_id, sport, requested_model, resolved_provider_model
order by preset_id, sport, requested_model, resolved_provider_model;

create view public.oauth_connections
with (security_invoker = true)
as
select
  user_id,
  client_name,
  count(*) as token_rows,
  min(created_at) as first_seen,
  max(created_at) as last_refresh,
  count(*) filter (
    where grant_type = 'authorization_code'
  ) as auth_grants,
  bool_or(
    revoked_at is null
    and coalesce(refresh_token_expires_at, 'infinity'::timestamptz) > now()
  ) as connected
from public.oauth_tokens
group by user_id, client_name;

create view analytics.usage_daily as
with ev as (
  select
    user_id,
    ts,
    (ts at time zone 'America/New_York')::date as et_day
  from public.mcp_tool_events
  where env = 'prod'
    and auth_type = 'oauth'
    and user_id not in (select user_id from analytics.internal_users)
),
firsts as (
  select
    user_id,
    min((ts at time zone 'America/New_York')::date) as first_day
  from ev
  group by user_id
),
daily as (
  select
    et_day,
    count(distinct user_id) as real_queriers,
    count(*) as calls,
    min(ts) as first_ev,
    max(ts) as last_ev
  from ev
  group by et_day
),
new_faces as (
  select first_day as et_day, count(*) as new_faces
  from firsts
  group by first_day
)
select
  d.et_day,
  d.real_queriers,
  d.calls,
  to_char(d.first_ev at time zone 'America/New_York', 'HH24:MI') as first_ev_et,
  to_char(d.last_ev at time zone 'America/New_York', 'HH24:MI') as last_ev_et,
  coalesce(n.new_faces, 0::bigint) as new_faces,
  sum(coalesce(n.new_faces, 0::bigint)) over (
    order by d.et_day
  ) as cumulative_distinct
from daily d
left join new_faces n using (et_day);

create view analytics.usage_rolling as
with ev as (
  select user_id, ts
  from public.mcp_tool_events
  where env = 'prod'
    and auth_type = 'oauth'
    and user_id not in (select user_id from analytics.internal_users)
)
select
  (
    select count(distinct user_id)
    from ev
    where ts >= now() - interval '7 days'
  )::integer as wau,
  (
    select count(distinct user_id)
    from ev
    where ts >= now() - interval '30 days'
  )::integer as mau,
  (select count(distinct user_id) from ev)::integer as cumulative_users,
  (
    select count(*)
    from ev
    where ts >= now() - interval '7 days'
  )::integer as calls_7d,
  (
    select count(distinct user_id)
    from ev
    where ts >= now() - interval '1 day'
  )::integer as dau;

create view analytics.usage_trend as
with ev as (
  select distinct
    user_id as uid,
    (ts at time zone 'America/New_York')::date as et_day
  from public.mcp_tool_events
  where env = 'prod'
    and auth_type = 'oauth'
    and user_id is not null
    and user_id not in (select user_id from analytics.internal_users)
),
firsts as (
  select uid, min(et_day) as first_day
  from ev
  group by uid
),
daily as (
  select et_day, count(distinct uid) as dau
  from ev
  group by et_day
),
newd as (
  select first_day as et_day, count(*) as new_users
  from firsts
  group by first_day
),
bounds as (
  select min(et_day) as lo, max(et_day) as hi
  from ev
),
days as (
  select generate_series(lo, hi, interval '1 day')::date as et_day
  from bounds
  where lo is not null
)
select
  d.et_day::text as et_day,
  coalesce(da.dau, 0)::integer as dau,
  (
    select count(distinct e.uid)::integer
    from ev e
    where e.et_day > d.et_day - 7
      and e.et_day <= d.et_day
  ) as wau_7d,
  coalesce(nw.new_users, 0)::integer as new_users,
  (coalesce(da.dau, 0) - coalesce(nw.new_users, 0))::integer
    as returning_users
from days d
left join daily da on da.et_day = d.et_day
left join newd nw on nw.et_day = d.et_day
order by d.et_day;

create view analytics.usage_totals as
select
  count(distinct user_id) filter (
    where (ts at time zone 'America/New_York')
      >= date_trunc('year', now() at time zone 'America/New_York')
  )::integer as ytd_users,
  count(distinct user_id)::integer as alltime_users,
  count(*) filter (
    where (ts at time zone 'America/New_York')
      >= date_trunc('year', now() at time zone 'America/New_York')
  )::integer as ytd_calls,
  count(*)::integer as alltime_calls
from public.mcp_tool_events
where env = 'prod'
  and auth_type = 'oauth'
  and user_id is not null
  and user_id not in (select user_id from analytics.internal_users);

create view analytics.client_mix as
with per_user as (
  select client_name, user_id, sum(call_count) as calls
  from public.mcp_user_daily
  where env = 'prod'
    and auth_type = 'oauth'
    and user_id not in (select user_id from analytics.internal_users)
  group by client_name, user_id
)
select
  coalesce(client_name, '(none)') as ai_client,
  count(*)::integer as users,
  sum(calls)::integer as calls,
  round(sum(calls)::numeric / nullif(count(*), 0), 1) as calls_per_user,
  round(
    percentile_cont(0.5) within group (order by calls)::numeric,
    1
  ) as median_per_user
from per_user
group by client_name
order by sum(calls) desc;

create view analytics.tool_health as
select
  tool_name,
  count(*)::integer as calls,
  count(*) filter (where status <> 'ok')::integer as error_calls,
  round(
    100.0
      * count(*) filter (where status <> 'ok')::numeric
      / count(*)::numeric,
    1
  ) as error_pct,
  percentile_cont(0.5) within group (
    order by latency_ms::double precision
  )::integer as p50_ms,
  percentile_cont(0.95) within group (
    order by latency_ms::double precision
  )::integer as p95_ms
from public.mcp_tool_events
where env = 'prod'
  and auth_type = 'oauth'
  and user_id not in (select user_id from analytics.internal_users)
group by tool_name
order by count(*) desc;

create view analytics.tool_health_7d as
select
  tool_name,
  count(*)::integer as calls,
  count(*) filter (where status <> 'ok')::integer as error_calls,
  round(
    100.0
      * count(*) filter (where status <> 'ok')::numeric
      / count(*)::numeric,
    1
  ) as error_pct,
  percentile_cont(0.5) within group (
    order by latency_ms::double precision
  )::integer as p50_ms,
  percentile_cont(0.95) within group (
    order by latency_ms::double precision
  )::integer as p95_ms
from public.mcp_tool_events
where env = 'prod'
  and auth_type = 'oauth'
  and ts >= now() - interval '7 days'
  and user_id not in (select user_id from analytics.internal_users)
group by tool_name
order by count(*) desc;

create view analytics.health_summary as
select
  count(*)::integer as calls,
  count(*) filter (where status <> 'ok')::integer as error_calls,
  round(
    100.0
      * count(*) filter (where status <> 'ok')::numeric
      / nullif(count(*), 0)::numeric,
    1
  ) as error_pct,
  percentile_cont(0.5) within group (
    order by latency_ms::double precision
  )::integer as p50_ms,
  percentile_cont(0.95) within group (
    order by latency_ms::double precision
  )::integer as p95_ms
from public.mcp_tool_events
where env = 'prod'
  and auth_type = 'oauth'
  and user_id not in (select user_id from analytics.internal_users);

create view analytics.health_summary_7d as
select
  count(*)::integer as calls,
  count(*) filter (where status <> 'ok')::integer as error_calls,
  round(
    100.0
      * count(*) filter (where status <> 'ok')::numeric
      / nullif(count(*), 0)::numeric,
    1
  ) as error_pct,
  percentile_cont(0.5) within group (
    order by latency_ms::double precision
  )::integer as p50_ms,
  percentile_cont(0.95) within group (
    order by latency_ms::double precision
  )::integer as p95_ms
from public.mcp_tool_events
where env = 'prod'
  and auth_type = 'oauth'
  and ts >= now() - interval '7 days'
  and user_id not in (select user_id from analytics.internal_users);

create view analytics.user_concentration as
with per_user as (
  select
    user_id,
    count(*) as calls,
    mode() within group (order by client_name) as client,
    min(ts) as first_ts
  from public.mcp_tool_events
  where env = 'prod'
    and auth_type = 'oauth'
    and user_id not in (select user_id from analytics.internal_users)
  group by user_id
),
ranked as (
  select
    row_number() over (order by calls desc) as rank,
    calls,
    client,
    first_ts,
    sum(calls) over () as total
  from per_user
)
select
  rank::integer as rank,
  calls::integer as calls,
  round(100.0 * calls::numeric / total, 1) as pct_of_calls,
  round(
    100.0 * sum(calls) over (order by rank) / total,
    1
  ) as cumulative_pct,
  client,
  to_char(first_ts at time zone 'America/New_York', 'Mon DD') as first_seen
from ranked
order by rank
limit 15;

create view analytics.platform_overlap as
with internal as (
  select user_id
  from analytics.internal_users
),
peruser as (
  select uid, count(*) as platforms
  from (
    select distinct clerk_user_id as uid
    from public.espn_leagues
    where clerk_user_id is not null

    union all

    select distinct clerk_user_id
    from public.yahoo_leagues
    where clerk_user_id is not null

    union all

    select distinct clerk_user_id
    from public.sleeper_leagues
    where clerk_user_id is not null
  ) x
  where uid not in (select user_id from internal)
  group by uid
)
select platforms::integer as platform_count, count(*)::integer as users
from peruser
group by platforms
order by platforms;

create view analytics.platform_summary as
with conn as (
  select clerk_user_id as uid, 'espn'::text as platform, season_year
  from public.espn_leagues

  union all

  select clerk_user_id, 'yahoo', season_year
  from public.yahoo_leagues

  union all

  select clerk_user_id, 'sleeper', season_year
  from public.sleeper_leagues
)
select
  platform,
  count(distinct uid)::integer as users,
  count(*) filter (where season_year = 2026)::integer as leagues_current,
  count(*)::integer as leagues_total
from conn
where uid not in (select user_id from analytics.internal_users)
group by platform
order by count(distinct uid) desc;

create view analytics.sport_summary as
with conn as (
  select clerk_user_id as uid, sport, season_year
  from public.espn_leagues

  union all

  select clerk_user_id, sport, season_year
  from public.yahoo_leagues

  union all

  select clerk_user_id, sport, season_year
  from public.sleeper_leagues
)
select
  coalesce(sport, '(none)') as sport,
  count(distinct uid)::integer as users,
  count(*)::integer as leagues,
  count(*) filter (where season_year = 2026)::integer as leagues_2026,
  count(*) filter (where season_year = 2025)::integer as leagues_2025
from conn
where uid not in (select user_id from analytics.internal_users)
group by sport
order by count(distinct uid) desc;

create view analytics.funnel_snapshot as
with internal as (
  select user_id
  from analytics.internal_users
),
oauth as (
  select distinct user_id as uid
  from public.oauth_tokens
  where user_id is not null
    and user_id not in (select user_id from internal)
),
creds as (
  select uid
  from (
    select clerk_user_id as uid
    from public.espn_credentials
    where clerk_user_id is not null

    union

    select clerk_user_id
    from public.yahoo_credentials
    where clerk_user_id is not null

    union

    select clerk_user_id
    from public.sleeper_connections
    where clerk_user_id is not null
  ) c
  where uid not in (select user_id from internal)
),
leagues as (
  select uid
  from (
    select clerk_user_id as uid
    from public.espn_leagues
    where clerk_user_id is not null

    union

    select clerk_user_id
    from public.yahoo_leagues
    where clerk_user_id is not null

    union

    select clerk_user_id
    from public.sleeper_leagues
    where clerk_user_id is not null
  ) l
  where uid not in (select user_id from internal)
),
queried as (
  select distinct user_id as uid
  from public.mcp_tool_events
  where env = 'prod'
    and auth_type = 'oauth'
    and user_id is not null
    and user_id not in (select user_id from internal)
),
known as (
  select uid from oauth
  union select uid from creds
  union select uid from leagues
  union select uid from queried
)
select
  1 as sort_order,
  'total_known'::text as stage,
  (select count(*) from known)::integer as users
union all
select 2, 'authorized_connector', (select count(*) from oauth)::integer
union all
select 3, 'captured_creds', (select count(*) from creds)::integer
union all
select 4, 'connected_league', (select count(*) from leagues)::integer
union all
select 5, 'queried_ever', (select count(*) from queried)::integer
union all
select
  6,
  'both_connector_and_league',
  (
    select count(*)
    from oauth o
    where exists (select 1 from leagues l where l.uid = o.uid)
  )::integer
union all
select
  7,
  'leak_connector_no_league',
  (
    select count(*)
    from oauth o
    where not exists (select 1 from leagues l where l.uid = o.uid)
  )::integer
union all
select
  8,
  'leak_league_no_connector',
  (
    select count(*)
    from leagues l
    where not exists (select 1 from oauth o where o.uid = l.uid)
  )::integer
union all
select
  9,
  'leak_creds_no_league',
  (
    select count(*)
    from creds c
    where not exists (select 1 from leagues l where l.uid = c.uid)
  )::integer
order by sort_order;

create or replace function analytics.dashboard_payload(
  include_internal boolean
)
returns jsonb
language sql
stable
set search_path to ''
as $function$
with excluded as (
  select user_id
  from analytics.internal_users
  where not include_internal
)
select jsonb_build_object(
  'usage_trend',
  (
    select coalesce(jsonb_agg(u order by u.et_day), '[]'::jsonb)
    from (
      with ev as (
        select distinct
          user_id as uid,
          (ts at time zone 'America/New_York')::date as et_day
        from public.mcp_tool_events
        where env = 'prod'
          and auth_type = 'oauth'
          and user_id is not null
          and user_id not in (select user_id from excluded)
      ),
      firsts as (
        select uid, min(et_day) as first_day
        from ev
        group by uid
      ),
      daily as (
        select et_day, count(distinct uid) as dau
        from ev
        group by et_day
      ),
      newd as (
        select first_day as et_day, count(*) as new_users
        from firsts
        group by first_day
      ),
      bounds as (
        select min(et_day) as lo, max(et_day) as hi
        from ev
      ),
      days as (
        select generate_series(lo, hi, interval '1 day')::date as et_day
        from bounds
        where lo is not null
      )
      select
        d.et_day::text as et_day,
        coalesce(da.dau, 0)::integer as dau,
        (
          select count(distinct e.uid)::integer
          from ev e
          where e.et_day > d.et_day - 7
            and e.et_day <= d.et_day
        ) as wau_7d,
        coalesce(nw.new_users, 0)::integer as new_users,
        (coalesce(da.dau, 0) - coalesce(nw.new_users, 0))::integer
          as returning_users
      from days d
      left join daily da on da.et_day = d.et_day
      left join newd nw on nw.et_day = d.et_day
    ) u
  ),
  'retention_weekly',
  (
    select coalesce(jsonb_agg(rw order by rw.week_start), '[]'::jsonb)
    from (
      with evd as (
        select distinct
          user_id as uid,
          (ts at time zone 'America/New_York')::date as et_day
        from public.mcp_tool_events
        where env = 'prod'
          and auth_type = 'oauth'
          and user_id is not null
          and user_id not in (select user_id from excluded)
      ),
      ev as (
        select distinct uid, date_trunc('week', et_day)::date as wk
        from evd
      ),
      this_wk as (
        select date_trunc(
          'week',
          now() at time zone 'America/New_York'
        )::date as wk
      ),
      bounds as (
        select
          min(et_day) as first_day,
          date_trunc('week', min(et_day))::date as first_wk
        from evd
      ),
      weeks as (
        select generate_series(
          first_wk,
          (select wk from this_wk),
          interval '7 days'
        )::date as wk
        from bounds
        where first_wk is not null
      ),
      cohorts as (
        select wk, count(*) as queriers
        from ev
        group by wk
      ),
      returns as (
        select e.wk, count(*) as returned
        from ev e
        where exists (
          select 1
          from ev n
          where n.uid = e.uid
            and n.wk = e.wk + 7
        )
        group by e.wk
      )
      select
        w.wk::text as week_start,
        coalesce(c.queriers, 0)::integer as queriers,
        case
          when w.wk >= t.wk then null
          else coalesce(r.returned, 0)::integer
        end as returned_next,
        case
          when w.wk >= t.wk then null
          else round(
            100.0
              * coalesce(r.returned, 0)
              / nullif(c.queriers, 0),
            1
          )
        end as return_pct,
        (w.wk < (select first_day from bounds)) as week_partial_start,
        (w.wk >= t.wk) as week_open,
        (w.wk < t.wk and w.wk + 7 >= t.wk) as next_week_open
      from weeks w
      cross join this_wk t
      left join cohorts c on c.wk = w.wk
      left join returns r on r.wk = w.wk
    ) rw
  ),
  'totals',
  (
    select to_jsonb(t)
    from (
      select
        count(distinct user_id) filter (
          where (ts at time zone 'America/New_York')
            >= date_trunc(
              'year',
              now() at time zone 'America/New_York'
            )
        )::integer as ytd_users,
        count(distinct user_id)::integer as alltime_users,
        count(*) filter (
          where (ts at time zone 'America/New_York')
            >= date_trunc(
              'year',
              now() at time zone 'America/New_York'
            )
        )::integer as ytd_calls,
        count(*)::integer as alltime_calls
      from public.mcp_tool_events
      where env = 'prod'
        and auth_type = 'oauth'
        and user_id is not null
        and user_id not in (select user_id from excluded)
    ) t
  ),
  'funnel',
  (
    select coalesce(jsonb_agg(f order by f.sort_order), '[]'::jsonb)
    from (
      with oauth as (
        select distinct user_id as uid
        from public.oauth_tokens
        where user_id is not null
          and user_id not in (select user_id from excluded)
      ),
      creds as (
        select uid
        from (
          select clerk_user_id as uid
          from public.espn_credentials
          where clerk_user_id is not null
          union
          select clerk_user_id
          from public.yahoo_credentials
          where clerk_user_id is not null
          union
          select clerk_user_id
          from public.sleeper_connections
          where clerk_user_id is not null
        ) c
        where uid not in (select user_id from excluded)
      ),
      leagues as (
        select uid
        from (
          select clerk_user_id as uid
          from public.espn_leagues
          where clerk_user_id is not null
          union
          select clerk_user_id
          from public.yahoo_leagues
          where clerk_user_id is not null
          union
          select clerk_user_id
          from public.sleeper_leagues
          where clerk_user_id is not null
        ) l
        where uid not in (select user_id from excluded)
      ),
      queried as (
        select distinct user_id as uid
        from public.mcp_tool_events
        where env = 'prod'
          and auth_type = 'oauth'
          and user_id is not null
          and user_id not in (select user_id from excluded)
      ),
      known as (
        select uid from oauth
        union select uid from creds
        union select uid from leagues
        union select uid from queried
      )
      select
        1 as sort_order,
        'total_known'::text as stage,
        (select count(*) from known)::integer as users
      union all
      select 2, 'authorized_connector', (select count(*) from oauth)::integer
      union all
      select 3, 'captured_creds', (select count(*) from creds)::integer
      union all
      select 4, 'connected_league', (select count(*) from leagues)::integer
      union all
      select 5, 'queried_ever', (select count(*) from queried)::integer
      union all
      select
        6,
        'both_connector_and_league',
        (
          select count(*)
          from oauth o
          where exists (select 1 from leagues l where l.uid = o.uid)
        )::integer
      union all
      select
        7,
        'leak_connector_no_league',
        (
          select count(*)
          from oauth o
          where not exists (select 1 from leagues l where l.uid = o.uid)
        )::integer
      union all
      select
        8,
        'leak_league_no_connector',
        (
          select count(*)
          from leagues l
          where not exists (select 1 from oauth o where o.uid = l.uid)
        )::integer
      union all
      select
        9,
        'leak_creds_no_league',
        (
          select count(*)
          from creds c
          where not exists (select 1 from leagues l where l.uid = c.uid)
        )::integer
    ) f
  ),
  'rolling',
  (
    select to_jsonb(r)
    from (
      with ev as (
        select user_id, ts
        from public.mcp_tool_events
        where env = 'prod'
          and auth_type = 'oauth'
          and user_id not in (select user_id from excluded)
      )
      select
        (
          select count(distinct user_id)
          from ev
          where ts >= now() - interval '7 days'
        )::integer as wau,
        (
          select count(distinct user_id)
          from ev
          where ts >= now() - interval '30 days'
        )::integer as mau,
        (select count(distinct user_id) from ev)::integer
          as cumulative_users,
        (
          select count(*)
          from ev
          where ts >= now() - interval '7 days'
        )::integer as calls_7d,
        (
          select count(distinct user_id)
          from ev
          where ts >= now() - interval '1 day'
        )::integer as dau
    ) r
  ),
  'health_summary',
  (
    select to_jsonb(h)
    from (
      select
        count(*)::integer as calls,
        count(*) filter (where status <> 'ok')::integer as error_calls,
        round(
          100.0
            * count(*) filter (where status <> 'ok')::numeric
            / nullif(count(*), 0),
          1
        ) as error_pct,
        percentile_cont(0.5) within group (
          order by latency_ms::double precision
        )::integer as p50_ms,
        percentile_cont(0.95) within group (
          order by latency_ms::double precision
        )::integer as p95_ms
      from public.mcp_tool_events
      where env = 'prod'
        and auth_type = 'oauth'
        and user_id not in (select user_id from excluded)
    ) h
  ),
  'health_summary_7d',
  (
    select to_jsonb(h7)
    from (
      select
        count(*)::integer as calls,
        count(*) filter (where status <> 'ok')::integer as error_calls,
        round(
          100.0
            * count(*) filter (where status <> 'ok')::numeric
            / nullif(count(*), 0),
          1
        ) as error_pct,
        percentile_cont(0.5) within group (
          order by latency_ms::double precision
        )::integer as p50_ms,
        percentile_cont(0.95) within group (
          order by latency_ms::double precision
        )::integer as p95_ms
      from public.mcp_tool_events
      where env = 'prod'
        and auth_type = 'oauth'
        and ts >= now() - interval '7 days'
        and user_id not in (select user_id from excluded)
    ) h7
  ),
  'client_mix',
  (
    select coalesce(jsonb_agg(c order by c.calls desc), '[]'::jsonb)
    from (
      with per_user as (
        select client_name, user_id, sum(call_count) as calls
        from public.mcp_user_daily
        where env = 'prod'
          and auth_type = 'oauth'
          and user_id not in (select user_id from excluded)
        group by client_name, user_id
      )
      select
        coalesce(client_name, '(none)') as ai_client,
        count(*)::integer as users,
        sum(calls)::integer as calls,
        round(sum(calls)::numeric / nullif(count(*), 0), 1)
          as calls_per_user,
        round(
          percentile_cont(0.5) within group (order by calls)::numeric,
          1
        ) as median_per_user
      from per_user
      group by client_name
    ) c
  ),
  'tool_health',
  (
    select coalesce(jsonb_agg(th order by th.calls desc), '[]'::jsonb)
    from (
      select
        tool_name,
        count(*)::integer as calls,
        count(*) filter (where status <> 'ok')::integer as error_calls,
        round(
          100.0
            * count(*) filter (where status <> 'ok')::numeric
            / count(*)::numeric,
          1
        ) as error_pct,
        percentile_cont(0.5) within group (
          order by latency_ms::double precision
        )::integer as p50_ms,
        percentile_cont(0.95) within group (
          order by latency_ms::double precision
        )::integer as p95_ms
      from public.mcp_tool_events
      where env = 'prod'
        and auth_type = 'oauth'
        and user_id not in (select user_id from excluded)
      group by tool_name
    ) th
  ),
  'tool_health_7d',
  (
    select coalesce(jsonb_agg(t7 order by t7.calls desc), '[]'::jsonb)
    from (
      select
        tool_name,
        count(*)::integer as calls,
        count(*) filter (where status <> 'ok')::integer as error_calls,
        round(
          100.0
            * count(*) filter (where status <> 'ok')::numeric
            / count(*)::numeric,
          1
        ) as error_pct,
        percentile_cont(0.5) within group (
          order by latency_ms::double precision
        )::integer as p50_ms,
        percentile_cont(0.95) within group (
          order by latency_ms::double precision
        )::integer as p95_ms
      from public.mcp_tool_events
      where env = 'prod'
        and auth_type = 'oauth'
        and ts >= now() - interval '7 days'
        and user_id not in (select user_id from excluded)
      group by tool_name
    ) t7
  ),
  'platform_summary',
  (
    select coalesce(jsonb_agg(p order by p.users desc), '[]'::jsonb)
    from (
      with conn as (
        select
          clerk_user_id as uid,
          'espn'::text as platform,
          season_year
        from public.espn_leagues
        union all
        select clerk_user_id, 'yahoo', season_year
        from public.yahoo_leagues
        union all
        select clerk_user_id, 'sleeper', season_year
        from public.sleeper_leagues
      )
      select
        platform,
        count(distinct uid)::integer as users,
        count(*) filter (where season_year = 2026)::integer
          as leagues_current,
        count(*)::integer as leagues_total
      from conn
      where uid not in (select user_id from excluded)
      group by platform
    ) p
  ),
  'platform_overlap',
  (
    select coalesce(
      jsonb_agg(o order by o.platform_count),
      '[]'::jsonb
    )
    from (
      with peruser as (
        select uid, count(*) as platforms
        from (
          select distinct clerk_user_id as uid
          from public.espn_leagues
          where clerk_user_id is not null
          union all
          select distinct clerk_user_id
          from public.yahoo_leagues
          where clerk_user_id is not null
          union all
          select distinct clerk_user_id
          from public.sleeper_leagues
          where clerk_user_id is not null
        ) x
        where uid not in (select user_id from excluded)
        group by uid
      )
      select
        platforms::integer as platform_count,
        count(*)::integer as users
      from peruser
      group by platforms
    ) o
  ),
  'sport_summary',
  (
    select coalesce(jsonb_agg(s order by s.users desc), '[]'::jsonb)
    from (
      with conn as (
        select clerk_user_id as uid, sport, season_year
        from public.espn_leagues
        union all
        select clerk_user_id, sport, season_year
        from public.yahoo_leagues
        union all
        select clerk_user_id, sport, season_year
        from public.sleeper_leagues
      )
      select
        coalesce(sport, '(none)') as sport,
        count(distinct uid)::integer as users,
        count(*)::integer as leagues,
        count(*) filter (where season_year = 2026)::integer as leagues_2026,
        count(*) filter (where season_year = 2025)::integer as leagues_2025
      from conn
      where uid not in (select user_id from excluded)
      group by sport
    ) s
  ),
  'user_concentration',
  (
    select coalesce(jsonb_agg(uc order by uc.rank), '[]'::jsonb)
    from (
      with per_user as (
        select
          user_id,
          count(*) as calls,
          mode() within group (order by client_name) as client,
          min(ts) as first_ts
        from public.mcp_tool_events
        where env = 'prod'
          and auth_type = 'oauth'
          and user_id not in (select user_id from excluded)
        group by user_id
      ),
      ranked as (
        select
          row_number() over (order by calls desc) as rank,
          calls,
          client,
          first_ts,
          sum(calls) over () as total
        from per_user
      )
      select
        rank::integer as rank,
        calls::integer as calls,
        round(100.0 * calls::numeric / total, 1) as pct_of_calls,
        round(
          100.0 * sum(calls) over (order by rank) / total,
          1
        ) as cumulative_pct,
        client,
        to_char(
          first_ts at time zone 'America/New_York',
          'Mon DD'
        ) as first_seen
      from ranked
      order by rank
      limit 15
    ) uc
  ),
  'connector_health',
  (
    select jsonb_build_object(
      'yahoo',
      (
        select to_jsonb(y)
        from (
          select
            count(*)::integer as users,
            count(*) filter (where expires_at > now())::integer
              as token_fresh,
            count(*) filter (
              where updated_at >= now() - interval '7 days'
            )::integer as rotated_7d,
            count(*) filter (
              where refresh_lease_owner is not null
                and refresh_lease_owner not like 'cooldown:%'
                and refresh_lease_expires_at > now()
            )::integer as live_refresh_leases,
            count(app_fingerprint)::integer as fingerprint_stamped,
            count(distinct app_fingerprint)::integer
              as fingerprint_variants
          from public.yahoo_credentials
          where clerk_user_id not in (select user_id from excluded)
        ) y
      ),
      'espn',
      (
        select to_jsonb(e)
        from (
          select
            count(*)::integer as users,
            count(*) filter (
              where updated_at >= now() - interval '90 days'
            )::integer as updated_90d,
            count(*) filter (
              where updated_at < now() - interval '300 days'
            )::integer as aging_300d
          from public.espn_credentials
          where clerk_user_id not in (select user_id from excluded)
        ) e
      ),
      'sleeper',
      (
        select to_jsonb(sl)
        from (
          select count(*)::integer as users
          from public.sleeper_connections
          where clerk_user_id not in (select user_id from excluded)
        ) sl
      ),
      'mcp',
      (
        select to_jsonb(m)
        from (
          with latest as (
            select distinct on (user_id)
              user_id,
              revoked_at,
              refresh_token_expires_at
            from public.oauth_tokens
            where user_id is not null
              and user_id not in (select user_id from excluded)
            order by user_id, created_at desc
          )
          select
            count(*)::integer as users,
            count(*) filter (
              where revoked_at is null
                and (
                  refresh_token_expires_at is null
                  or refresh_token_expires_at > now()
                )
            )::integer as active,
            count(*) filter (
              where revoked_at is not null
                or refresh_token_expires_at <= now()
            )::integer as reconnect_needed
          from latest
        ) m
      ),
      'sync_7d',
      (
        select coalesce(
          jsonb_agg(sy order by sy.provider),
          '[]'::jsonb
        )
        from (
          select
            provider,
            count(*)::integer as users_attempted,
            count(*) filter (
              where last_success_at >= now() - interval '7 days'
            )::integer as succeeded_7d,
            count(*) filter (
              where last_failure_at >= now() - interval '7 days'
            )::integer as failed_7d,
            coalesce(
              array_agg(distinct last_error_code) filter (
                where last_error_code is not null
                  and last_failure_at >= now() - interval '7 days'
              ),
              '{}'
            ) as recent_error_codes
          from public.provider_sync_state
          where clerk_user_id not in (select user_id from excluded)
          group by provider
        ) sy
      )
    )
  ),
  'internal_user_count',
  (select count(*)::integer from analytics.internal_users)
)
$function$;

create or replace function analytics.refresh_dashboard_snapshot()
returns void
language plpgsql
set search_path to ''
as $function$
begin
  insert into analytics.dashboard_snapshot (id, payload, computed_at)
  values
    (1, analytics.dashboard_payload(false), now()),
    (2, analytics.dashboard_payload(true), now())
  on conflict (id) do update
  set payload = excluded.payload,
      computed_at = excluded.computed_at;
end;
$function$;

-- Reproduce the observed before-state privileges explicitly. These broad
-- privileges are part of the baseline so later hardening can be isolated,
-- reviewed, and reversed as a forward migration.
revoke create on schema public from public;
grant usage on schema public to public;

revoke all on schema analytics
from public, anon, authenticated, service_role, analytics_readonly;
grant usage on schema analytics to analytics_readonly;

revoke all privileges on all tables in schema public
from public, anon, authenticated, service_role, analytics_readonly;

grant all privileges on table
  public.espn_credentials,
  public.espn_leagues,
  public.oauth_codes,
  public.oauth_tokens,
  public.oauth_states,
  public.yahoo_credentials,
  public.yahoo_leagues,
  public.platform_oauth_states,
  public.user_preferences,
  public.sleeper_connections,
  public.sleeper_leagues,
  public.chat_runs,
  public.demo_context_cache,
  public.demo_answer_cache,
  public.demo_refresh_runs,
  public.demo_refresh_attempts,
  public.archived_leagues,
  public.mcp_tool_events,
  public.mcp_user_daily,
  public.mcp_tool_daily,
  public.provider_sync_state,
  public.demo_refresh_attempt_scorecard_7d,
  public.oauth_connections
to anon, authenticated;

grant all privileges on all tables in schema public to service_role;

revoke all privileges on all sequences in schema public
from public, anon, authenticated, service_role, analytics_readonly;
grant all privileges on all sequences in schema public
to anon, authenticated, service_role;

revoke all privileges on all functions in schema public
from public, anon, authenticated, service_role, analytics_readonly;
grant execute on all functions in schema public
to public, anon, authenticated, service_role;

revoke all privileges on all tables in schema analytics
from public, anon, authenticated, service_role, analytics_readonly;
grant select on all tables in schema analytics to analytics_readonly;

revoke all privileges on all functions in schema analytics
from public, anon, authenticated, service_role, analytics_readonly;
grant execute on all functions in schema analytics to public;

-- Preserve the current future-object behavior as an explicit before-state.
-- A later hardening migration will narrow these defaults after consumer proof.
alter default privileges for role postgres in schema public
  grant all privileges on tables to anon, authenticated, service_role;
alter default privileges for role postgres in schema public
  grant all privileges on sequences to anon, authenticated, service_role;
alter default privileges for role postgres in schema public
  revoke execute on functions from public;
alter default privileges for role postgres in schema public
  grant execute on functions to anon, authenticated, service_role;

-- supabase_admin is platform-owned. Supabase's roles bootstrap owns its
-- default ACLs, and application migrations are intentionally not permitted to
-- change them. Reset verification asserts those platform defaults separately.

alter default privileges for role postgres in schema analytics
  grant select on tables to analytics_readonly;
