name = "fantasy-sports-mcp"
main = "src/index.ts"
compatibility_date = "2024-12-01"

# JWT validation secret (shared with flaim-auth service)
# JWT_SECRET
# ENCRYPTION_KEY

# Durable Objects for user credential storage
[[durable_objects.bindings]]
name = "USER_DO"
class_name = "UserCredentials"
script_name = "fantasy-sports-mcp"

# Routes for ESPN MCP endpoints only
[[routes]]
pattern = "baseball-mcp.flaim.app/*"
zone_name = "flaim.app"

[[routes]]
pattern = "*/mcp*"
zone_name = "gerrygugger.workers.dev"

[[routes]]
pattern = "*/credential/espn*"
zone_name = "gerrygugger.workers.dev"

[env.dev]
name = "fantasy-sports-mcp-dev"

[[env.dev.durable_objects.bindings]]
name = "USER_DO"
class_name = "UserCredentials"
script_name = "fantasy-sports-mcp-dev"

[[env.dev.routes]]
pattern = "fantasy-sports-mcp-dev.gerrygugger.workers.dev/*"

# Durable Object migrations
[[migrations]]
tag = "v1"
new_sqlite_classes = ["UserCredentials"]

[env.prod]
name = "fantasy-sports-mcp-prod"

[[env.prod.durable_objects.bindings]]
name = "USER_DO"
class_name = "UserCredentials"
script_name = "fantasy-sports-mcp-prod"

[[env.prod.routes]]
pattern = "fantasy-sports-mcp-prod.gerrygugger.workers.dev/*"