name: Check Extension

on:
  push:
    branches:
      - main
    paths:
      - 'extension/**'
      - '.github/workflows/check-extension.yml'
  pull_request:
    paths:
      - 'extension/**'
      - '.github/workflows/check-extension.yml'
  workflow_dispatch:

jobs:
  check:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: '24'
          cache: 'npm'

      - name: Install Dependencies
        run: npm ci
        working-directory: extension

      - name: Build extension
        run: npm run build
        working-directory: extension
